export const USER_DETAIL = "USER_DETAIL";
export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";
export const ADD_USER_DETAIL = "ADD_USER_DETAIL";
export const FIRST_TIME_USER = "FIRST_TIME_USER";

export const CREATE_NOTEBOOK = "CREATE_NOTEBOOK";
export const FETCH_NOTEBOOKS = "FETCH_NOTEBOOKS";

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const NEW_TRANSACTION = "NEW_TRANSACTION";
