export const USER_DETAIL = "USER_DETAIL";
export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";

export const CREATE_NOTEBOOK = "CREATE_NOTEBOOK";
export const FETCH_NOTEBOOKS = "FETCH_NOTEBOOKS";

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
